def obnoxious_arpeggio(reps, w, x, y, z, *, tie=False, acc1=False, acc3=False, start_slur1=False, end_slur3=False):
    tie = "~" if tie else ""
    acc1 = "_>" if acc1 else ""
    acc3 = "_>" if acc3 else ""
    start_slur1 = "(" if start_slur1 else ""
    end_slur3 = ")" if end_slur3 else ""
    for _ in range(reps - 1):
        print(f"  \\tuplet 3/2 4 {{ {w}8{acc1}{start_slur1} {x}' {y}') {z}'( {y}, {x},}} {w},4~ |")
        acc1 = ""
        start_slur1 = ""
    print(f"  \\tuplet 3/2 4 {{ {w}8{acc1}{start_slur1} {x}' {y}') {z}'( {y}, {x},}} {w},4{acc3}{tie}{end_slur3} |")

a = "a"
bf = "bf"
c = "c"
cs = "cs"
d = "d"
ef = "ef"
e = "e"
f = "f"
fs = "fs"
g = "g"
T = True

print("  %%%%%%%% START AUTOGENERATED %%%%%%%%")
obnoxious_arpeggio(1, g, ef, c, g, tie=T, start_slur1=T)
print("  \\temporary\\omit TupletNumber")
print("  % PAGE 3 LINE 8")
print("  \\og_break")
obnoxious_arpeggio(1, g, ef, c, g, tie=T)
obnoxious_arpeggio(2, g, e,  c, g, acc3=T)
obnoxious_arpeggio(2, a, f,  c, a, tie=T, acc1=T)
obnoxious_arpeggio(1, a, e, cs, a, tie=T)
print("  % PAGE 3 LINE 9")
print("  \\og_break")
obnoxious_arpeggio(1,  a, e, cs, a, acc3=T)
obnoxious_arpeggio(2, bf, f,  d, bf, acc3=T)
obnoxious_arpeggio(1,  c, g,  e, c, tie=T)
obnoxious_arpeggio(1,  c, g, ef, c, acc3=T)
obnoxious_arpeggio(1,  d, a, fs, d, acc1=T, acc3=T)
print("  % PAGE 3 LINE 10")
print("  \\og_break")
obnoxious_arpeggio(1, ef, bf, g, ef, acc3=T)
obnoxious_arpeggio(1,  d,  a, fs, d, acc1=T, acc3=T)
obnoxious_arpeggio(1, ef, bf, g, ef, acc1=T, acc3=T)
obnoxious_arpeggio(1,  d,  a, fs, d, acc1=T, acc3=T)
obnoxious_arpeggio(2, ef, bf, g, ef, tie=T, acc1=T)
print("  % PAGE 3 LINE 11")
print("  \\og_break")
obnoxious_arpeggio(1, ef, bf, g, ef, end_slur3=T)
print("  %%%%%%%% END AUTOGENERATED %%%%%%%%")
